solution - AK
mate-academy/py-dockerize-cinema pull request #126
Opened 2023-03-16 15:08 UTC by AnnaKabatova

2023-03-16 18:24 UTC, ArsenPidhoretskyi requested changes

2023-03-16 18:24 UTC, ArsenPidhoretskyi commented on .env.sample
> +SECRET_KEY=SECRET_KEY
Add emply line

2023-03-16 18:24 UTC, ArsenPidhoretskyi commented on Dockerfile
> +USER django-user
Empty line

2023-03-16 18:24 UTC, ArsenPidhoretskyi commented on docker-compose.yml
> +      - .env
Empty line

2023-03-17 10:16 UTC, Bohdan-Salamakha requested changes
don't work on the master branch - bad practice
https://github.com/mate-academy/py-task-guideline/blob/main/README.md#:~:text=git%20checkout%20%2Db%20develop

2023-03-17 11:12 UTC, closed without merging